### ISSUE TITLE
How to set custom base url?

### ISSUE THREAD

**Issue by rajeev-k-tomy** [staempfli/magento2-builder-tool#4]
It would be great if we have a provision to set the base URL through the property configuration. Currently, there is no provision to do this.

I can see below code in the `build/xmlscripts/magento.xml`

    <target name="magento:install"
            depends="database:drop,
            database:create,
            magento:module:init"
            hidden="true">

        <customHook hook="before-magento-install"/>

        <echo message=""/>
        <echo message="Installing Magento..."/>

        <exec passthru="false"
              checkreturn="true"
              logoutput="true"
              command="${bin.n98-magerun2} setup:install
                --backend-frontname=&quot;${magento.admin.frontname}&quot;
                --db-host=&quot;${database.host}&quot;
                --db-name=&quot;${database.name}&quot;
                --db-user=&quot;${database.user}&quot;
                --db-password=&quot;${database.password}&quot;
                --base-url=&quot;http://${project.name}.lo&quot;
                --language=&quot;${install.locale}&quot;
                --timezone=&quot;${install.timezone}&quot;
                --currency=&quot;${install.currency}&quot;
                --admin-firstname=&quot;${install.admin.firstname}&quot;
                --admin-lastname=&quot;${install.admin.lastname}&quot;
                --admin-email=&quot;${install.admin.email}&quot;
                --admin-user=&quot;${install.admin.username}&quot;
                --admin-password=&quot;${install.admin.password}&quot;
                --use-rewrites=1
                --cleanup-database
                ${magento.setup.install.extra.params}
               "/>

        <customHook hook="after-magento-install"/>

    </target>

As we can see above, the base URL setting `--base-url=&quot;http://${project.name}.lo&quot;` seems hard coded here.

In my case, I want to set the URL to `domain.test`, but in order to make it work, I need to edit this file manually.

So any workaround for this? Please let me know.

___________

**Problem 2:** I am trying to use [**your blog**](https://blog.hauri.me/proper-magento2-composer-setup.html) instructions to setup an ideal magento working environment. But if I put all Magento codes inside `magento` directory, then I need to make the url like `domain.test/magento`. What should I do in order to access the site by simply calling `domain.test` with the help of this repository? 

Let me know your thoughts. Thank you in advance. This is a great tool.

**Comment by jalogut** [comment]
Hi @progammer-rkt 

## Problem 1: 
You can use any of the following ways of the following ways:

**Option 1**: `${project.name}` is resolved by default with the project folder name. So you could rename your project to `domain` and this value will be used. That will not change the `.lo`, so you will still get something like `domain.lo`

**Option 2**: You can set a value for any param during command execution. By doing that, the specified value will be used instead of the default one. That however will also not change the `.lo`.

```
bin/mg2-builder install -Dproject.name=domain
bin/mg2-builder sync -Dproject.name=domain
```

**Option 3**: If you want to change the whole url, you can do so by specifying this url in the `config.yml` file. There you can set the url for each of your stores. These values will always be used
at the end of `install` and `sync` commands. So just set your custom urls on `<your_project>/config/mg2-builder/magento/config.yml`:

- https://github.com/staempfli/magento2-builder-tool/blob/master/config.sample/mg2-builder/magento/config.yaml#L35

If you are also using the `apache` or `nginx` configuration, you will have to set your custom url also there `<your_project>/config/mg2-builder/vhost`

## Problem 2:

To directly point your urls into the `magento` dir, you need to specify that on your `apache` or `nginx` configuration. Just add `/magento` at the end of your `apache/nginx` configuration paths.

**Comment by rajeev-k-tomy** [comment]
@jalogut I think if we can provide the provision to set the base URL through the configuration files, then that will be a great advantage. 

I already specified `magento/config.yml` as you mentioned in option 3. But in that case, then Nginx configuration file generated with the URL `domain.lo`. So in order to make the URL universally apply everywhere, it would be better if we provide such overwriting provision for the same through the configuration file.

Regarding **problem 2**, I already figured it out. Thak you for pointing out here since it will be beneficial for future visitors.

Please consider this as a feature request.

**Comment by jalogut** [comment]
Hi @progammer-rkt 

Sure, as I mentioned in the other issue https://github.com/staempfli/magento2-builder-tool/issues/5 , feel free to create a PR for that. I'd glad to merge it then.
